configrate i3block

diff --git a/.config/i3/scripts/openweather-city b/.config/i3/scripts/openweather-city
--- a/.config/i3/scripts/openweather-city
+++ b/.config/i3/scripts/openweather-city
@@ -1,43 +1,49 @@
 #!/usr/bin/env bash
 
-command -v jq >/dev/null 2>&1 || { echo >&2 "Program 'jq' required but it is not installed.
-Aborting."; exit 1; }
-command -v curl >/dev/null 2>&1 || { echo >&2 "Program 'curl' required but is not installed.
-Aborting."; exit 1; }
+command -v jq >/dev/null 2>&1 || {
+  echo >&2 "Program 'jq' required but it is not installed.
+Aborting."
+  exit 1
+}
+command -v curl >/dev/null 2>&1 || {
+  echo >&2 "Program 'curl' required but is not installed.
+Aborting."
+  exit 1
+}
 
-# To use this script you need to create an API key here https://home.openweathermap.org
-# You need to put your Open Weather APIKEY here:
-APIKEY="keykey"
-# find your City ID here: https://openweathermap.org/
-# search for your city and copy the ID from the URL inside the browser.
-CITY_ID="idid"
-URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&units=metric&APPID=${APIKEY}"
+APIKEY="32fd7ed47937b14d10e29d05d30f166c"
+CITY_ID="610116"
+URL="https://restapi.amap.com/v3/weather/weatherInfo?key=${APIKEY}&city=${CITY_ID}&extensions=base"
 
-WEATHER_RESPONSE=$(timeout --signal=1 2s curl -s "${URL}") ||  exit 1;
+json=$(timeout --signal=1 2s curl -s "${URL}") || exit 1
 
-WEATHER_CONDITION=$(echo $WEATHER_RESPONSE | jq '.weather[0].main' | sed 's/"//g')
-WEATHER_TEMP=$(echo $WEATHER_RESPONSE | jq '.main.temp')
-WIND_DIR=$( echo "$WEATHER_RESPONSE" | jq '.wind.deg')
-WIND_SPEED=$( echo "$WEATHER_RESPONSE" | jq '.wind.speed')
+# {
+#     "status": "1",
+#     "count": "1",
+#     "info": "OK",
+#     "infocode": "10000",
+#     "lives": [
+#         {
+#             "province": "陕西",
+#             "city": "长安区",
+#             "adcode": "610116",
+#             "weather": "雾",
+#             "temperature": "3",
+#             "winddirection": "北",
+#             "windpower": "≤3",
+#             "humidity": "97",
+#             "reporttime": "2024-11-21 23:01:06",
+#             "temperature_float": "3.0",
+#             "humidity_float": "97.0"
+#         }
+#     ]
+# }
 
-WIND_SPEED=$(awk "BEGIN {print 60*60*$WIND_SPEED/1000}")
-WIND_DIR=$(awk "BEGIN {print int(($WIND_DIR % 360)/22.5)}")
-DIR_ARRAY=( N NNE NE ENE E ESE SE SSE S SSW SW WSW W WNW NW NNW N )
-WIND_DIR=${DIR_ARRAY[WIND_DIR]}
+PROVINCE=$(echo "$json" | jq -r '.lives[0].province')        # 城市
+CITY=$(echo "$json" | jq -r '.lives[0].city')                # 城市
+WEATHER_ICON=$(echo "$json" | jq -r '.lives[0].weather')     # 天气状况（如雾）
+WEATHER_TEMP=$(echo "$json" | jq -r '.lives[0].temperature') # 温度
+WIND_SPEED=$(echo "$json" | jq -r '.lives[0].windpower')     # 风速
+WIND_DIR=$(echo "$json" | jq -r '.lives[0].winddirection')   # 风向
 
-case $WEATHER_CONDITION in
-  'Clouds')
-    WEATHER_ICON=""
-    ;;
-  'Rain')
-    WEATHER_ICON=""
-    ;;
-  'Snow')
-    WEATHER_ICON=""
-    ;;
-  *)
-    WEATHER_ICON=""
-    ;;
-esac
-
-echo "${WEATHER_ICON}  ${WEATHER_TEMP}°C: ${WIND_SPEED} km/h ${WIND_DIR}"
+echo " ${PROVINCE}${CITY} ${WEATHER_ICON} ${WEATHER_TEMP}°C: ${WIND_SPEED} km/h ${WIND_DIR}"
